# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: https://registry.cn-zhangjiakou.aliyuncs.com
        logout: false
    
    # 使用shell命令批量同步所需的镜像到dockerHub中
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        docker run quay.io/skopeo/stable:latest copy -a --preserve-digests --remove-signatures --dest-username ${{ secrets.DOCKER_USERNAME }} --dest-password ${{ secrets.DOCKER_PASSWORD }} docker://quay.io/prometheus/prometheus:v3.0.1 docker://registry.cn-zhangjiakou.aliyuncs.com/lxiangxiang/prometheus:v3.0.1
        docker run quay.io/skopeo/stable:latest copy -a --preserve-digests --remove-signatures --dest-username ${{ secrets.DOCKER_USERNAME }} --dest-password ${{ secrets.DOCKER_PASSWORD }} docker://quay.io/prometheus/blackbox-exporter:v0.25.0 docker://registry.cn-zhangjiakou.aliyuncs.com/lxiangxiang/blackbox-exporter:v0.25.0
        docker run quay.io/skopeo/stable:latest copy -a --preserve-digests --remove-signatures --dest-username ${{ secrets.DOCKER_USERNAME }} --dest-password ${{ secrets.DOCKER_PASSWORD }} docker://ghcr.io/jimmidyson/configmap-reload:v0.14.0 docker://registry.cn-zhangjiakou.aliyuncs.com/lxiangxiang/configmap-reload:v0.14.0
        docker run quay.io/skopeo/stable:latest copy -a --preserve-digests --remove-signatures --dest-username ${{ secrets.DOCKER_USERNAME }} --dest-password ${{ secrets.DOCKER_PASSWORD }} docker://quay.io/brancz/kube-rbac-proxy:v0.18.2 docker://registry.cn-zhangjiakou.aliyuncs.com/lxiangxiang/kube-rbac-proxy:v0.18.2
        docker run quay.io/skopeo/stable:latest copy -a --preserve-digests --remove-signatures --dest-username ${{ secrets.DOCKER_USERNAME }} --dest-password ${{ secrets.DOCKER_PASSWORD }} docker://quay.io/prometheus-operator/prometheus-operator:v0.79.1 docker://registry.cn-zhangjiakou.aliyuncs.com/lxiangxiang/prometheus-operator:v0.79.1
        docker run quay.io/skopeo/stable:latest copy -a --preserve-digests --remove-signatures --dest-username ${{ secrets.DOCKER_USERNAME }} --dest-password ${{ secrets.DOCKER_PASSWORD }} docker://registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.14.0 docker://registry.cn-zhangjiakou.aliyuncs.com/lxiangxiang/kube-state-metrics:v2.14.0
        docker run quay.io/skopeo/stable:latest copy -a --preserve-digests --remove-signatures --dest-username ${{ secrets.DOCKER_USERNAME }} --dest-password ${{ secrets.DOCKER_PASSWORD }} docker://registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.12.0 docker://registry.cn-zhangjiakou.aliyuncs.com/lxiangxiang/prometheus-adapter:v0.12.0
        docker run quay.io/skopeo/stable:latest copy -a --preserve-digests --remove-signatures --dest-username ${{ secrets.DOCKER_USERNAME }} --dest-password ${{ secrets.DOCKER_PASSWORD }} docker://quay.io/prometheus/alertmanager:v0.27.0 docker://registry.cn-zhangjiakou.aliyuncs.com/lxiangxiang/alertmanager:v0.27.0
        docker run quay.io/skopeo/stable:latest copy -a --preserve-digests --remove-signatures --dest-username ${{ secrets.DOCKER_USERNAME }} --dest-password ${{ secrets.DOCKER_PASSWORD }} docker://quay.io/prometheus/node-exporter:v1.8.2 docker://registry.cn-zhangjiakou.aliyuncs.com/lxiangxiang/node-exporter:v1.8.2
        docker run quay.io/skopeo/stable:latest copy -a --preserve-digests --remove-signatures --dest-username ${{ secrets.DOCKER_USERNAME }} --dest-password ${{ secrets.DOCKER_PASSWORD }} docker://docker.io/grafana/grafana:11.4.0 docker://registry.cn-zhangjiakou.aliyuncs.com/lxiangxiang/grafana:11.4.0



