# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: https://registry.cn-zhangjiakou.aliyuncs.com
        logout: false
    
    # 使用shell命令批量同步所需的镜像到dockerHub中
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        skopeo copy --all docker://apache/skywalking-java-agent:9.3.0-java17 docker://registry.cn-zhangjiakou.aliyuncs.com/lxiangxiang/skywalking-java-agent:9.3.0-java17
        skopeo copy --all docker://apache/skywalking-java-agent:9.3.0-alpine docker://registry.cn-zhangjiakou.aliyuncs.com/lxiangxiang/skywalking-java-agent:9.3.0-alpine
        skopeo copy --all docker://apache/skywalking-oap-server:10.1.0 docker://registry.cn-zhangjiakou.aliyuncs.com/lxiangxiang/skywalking-oap-server:10.1.0
        skopeo copy --all docker://apache/skywalking-ui:10.1.0 docker://registry.cn-zhangjiakou.aliyuncs.com/lxiangxiang/skywalking-ui:10.1.0
        skopeo copy --all docker://apache/skywalking-banyandb:0.7.1 docker://registry.cn-zhangjiakou.aliyuncs.com/lxiangxiang/skywalking-banyandb:0.7.1
        skopeo copy --all docker://apache/skywalking-swck:v0.6.1 docker://registry.cn-zhangjiakou.aliyuncs.com/lxiangxiang/skywalking-swck:v0.6.1
